## FIT THE MODEL ON ALGORITHM AND USE TO MAKE PREDICTIONS

- FITTING THE MODEL
- `X` => features, feature variables, data
- `y` => labels, targets, target variables

In [13]:
import pandas as pd
import numpy as np

In [14]:
HEART_DISEASE_DATASET = "./data/heart-disease.csv"
heart_disease = pd.read_csv(HEART_DISEASE_DATASET)

In [15]:
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split

In [16]:
# SPLITTING THE DATA 

X = heart_disease.drop("target", axis=1)
y = heart_disease['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [17]:
# TRAINING THE MODEL 
np.random.seed(42)
clf = LinearSVC()

clf.fit(X_train, y_train)

/Users/macintosh/opt/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [18]:
# TESTING THE TRAINED MODEL WITH TESTING DATA 
# Evaluate
clf.score(X_test, y_test)

0.819672131147541

In [19]:
# USING TRAINED MODEL TO MAKEM PREDICTIONS
- 2 WAYS TO MAKE PREDICTIONS 
1. Using the `predict()` method/function 
2. Using the `predict_proba()` method/function 

In [20]:
# PREDICT METHOD 
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1])

In [21]:
# COMPARINT PREDICTIONS WITH ACTUAL TEST
np.array(y_test)

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [23]:
# COMPARING PREDICTIONS TO TRUTH LABELS TO EVALUATE MODEL 

y_preds = clf.predict(X_test)
np.mean(y_preds == y_test) # Gives the percentage of predictions. Same as clf.score(X_test, y_test)

0.819672131147541

In [24]:
# ANOTHER METHOD OF EVALUATING MODEL 
from sklearn.metrics import accuracy_score

# accuracy classification score
accuracy_score(y_test, y_preds) # Gives the percentage of predictions. Same as clf.score(X_test, y_test)

0.819672131147541

In [26]:
# MAKE PREDICTIONS WITH predict_proba

clf.predict(X_test[:5])

array([0, 1, 1, 0, 1])

In [28]:
y_test[:5]

180    0
154    1
111    1
247    0
60     1
Name: target, dtype: int64

In [29]:
# predict_proba(X_test) # makes two probabilities and uses it to predict the result or label
[[0.89, 0.11],
 [0.11, 0.89],
 [0.49, 0.51]
]

[[0.89, 0.11], [0.11, 0.89], [0.49, 0.51]]

In [30]:

from sklearn.ensemble import RandomForestClassifier

rfc_model = RandomForestClassifier()

rfc_model.fit(X_train, y_train)

rfc_model.score(X_test, y_test)

0.9180327868852459

In [31]:
rfc_model.predict_proba(X_test[:5])

array([[0.94, 0.06],
       [0.04, 0.96],
       [0.44, 0.56],
       [0.53, 0.47],
       [0.15, 0.85]])

In [32]:
rfc_model.predict(X_test[:5])

array([0, 1, 1, 0, 1])

# MAKING PREDICTIONS WITH REGRESSION USING BOSTON DATA

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_boston

boston_df = load_boston()
X_boston = pd.DataFrame(boston.data, columns=boston.feature_names)
y_boston = pd.Series(boston.target)

/Users/macintosh/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California h

In [43]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

# X = boston_df.drop("target", axis=1)
# y = boston_df["target"]

X_train, X_test, y_train, y_test = train_test_split(X_boston, y_boston, test_size=0.2, random_state=42)


# Instantiate RandomForestRegressor

rf_model = RandomForestRegressor().fit(X_train, y_train)

rf_model.score(X_test, y_test)

0.8922527442109116

In [44]:
# MAKING PREDICTIONS
y_preds = rf_model.predict(X_test[:5])

In [46]:
y_preds

array([22.839, 30.676, 16.317, 23.51 , 16.819])

In [45]:
np.array(y_test[:5])

array([23.6, 32.4, 13.6, 22.8, 16.1])

In [47]:
# COMPARING PREDICTIONS TO THE TRUTH 

from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

ValueError: Found input variables with inconsistent numbers of samples: [102, 5]